version: 2
updates:
  - package-ecosystem: npm
    directory: /site
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Etc/UTC
    groups:
      site-dependencies:
        patterns:
          - "*"
    commit-message:
      prefix: "deps(site)"

  - package-ecosystem: npm
    directory: /management-console/web
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Etc/UTC
    groups:
      management-console-web:
        patterns:
          - "*"
    commit-message:
      prefix: "deps(console-web)"

  - package-ecosystem: nuget
    directory: /management-console/api
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Etc/UTC
    groups:
      management-console-api:
        patterns:
          - "*"
    commit-message:
      prefix: "deps(console-api)"
